#!/bin/sh
# Dell Discovery Canvas — LLM proxy snippet generator.
#
# Generates /etc/nginx/snippets/llm-proxy.conf with reverse-proxy
# location blocks so the browser can reach LLM endpoints without CORS:
#   /api/llm/local/*      -> http://${LLM_HOST}:${LLM_LOCAL_PORT}/
#   /api/llm/local-b/*    -> http://${LLM_HOST}:${LLM_LOCAL_B_PORT}/   (rc.4-dev hotfix2a)
#   /api/llm/anthropic/*  -> https://api.anthropic.com/
#   /api/llm/gemini/*     -> https://generativelanguage.googleapis.com/
#
# LLM_HOST defaults to host.docker.internal (works on Docker Desktop and
# on Linux Docker 20.10+ with the host-gateway extra-hosts mapping in
# docker-compose.yml). Override per deployment by setting the env var.
#
# Per LLMs on GB10.docx (user reference doc, 2026-04-23):
#   - Code LLM (Qwen3-Coder-Next-FP8) on port 8000  -> Local A
#     (--enable-auto-tool-choice --tool-call-parser hermes; tool-use
#     capable for selectGapsKanban / selectMatrixView / etc. multi-
#     round chains)
#   - VLM (Qwen2.5-VL-7B-Instruct)    on port 8001  -> Local B
#     (vision-language; image_url content blocks; no tool parser)
# Both expose OpenAI-compatible REST at /v1/chat/completions, /v1/models,
# /health.
#
# All four locations use proxy_buffering off + extended timeouts so SSE
# streaming chunks pass through unbuffered + multi-round tool chains
# (30-60s per round on slow LLMs) don't time out.
#
# Invoked automatically by the upstream nginx:alpine entrypoint chain.

set -eu

SNIPPETS_DIR="/etc/nginx/snippets"
LLM_INCLUDE="${SNIPPETS_DIR}/llm-proxy.conf"

LLM_HOST="${LLM_HOST:-host.docker.internal}"
LLM_LOCAL_PORT="${LLM_LOCAL_PORT:-8000}"
LLM_LOCAL_B_PORT="${LLM_LOCAL_B_PORT:-8001}"

mkdir -p "$SNIPPETS_DIR"

cat > "$LLM_INCLUDE" <<EOF
# Generated by docker-entrypoint.d/45-setup-llm-proxy.sh from env vars.
# LLM_HOST=${LLM_HOST}, LLM_LOCAL_PORT=${LLM_LOCAL_PORT}, LLM_LOCAL_B_PORT=${LLM_LOCAL_B_PORT}.

# Local self-hosted vLLM A (Code LLM per LLMs on GB10.docx, default port 8000).
location /api/llm/local/ {
  access_log off;
  proxy_pass http://${LLM_HOST}:${LLM_LOCAL_PORT}/;
  proxy_http_version 1.1;
  proxy_set_header Host \$host;
  proxy_set_header X-Real-IP \$remote_addr;
  # Streaming-friendly: SSE chunks need buffering off; multi-round
  # tool chains can take 30-60s per round on a slow local LLM.
  proxy_buffering off;
  proxy_request_buffering off;
  proxy_read_timeout 600s;
  proxy_send_timeout 600s;
}

# rc.4-dev hotfix2a (2026-05-04): Local self-hosted vLLM B (VLM per
# LLMs on GB10.docx, default port 8001). Same streaming-friendly
# tuning as Local A. Mirror config so a user can run two vLLM
# endpoints (e.g. code + vision) side-by-side.
location /api/llm/local-b/ {
  access_log off;
  proxy_pass http://${LLM_HOST}:${LLM_LOCAL_B_PORT}/;
  proxy_http_version 1.1;
  proxy_set_header Host \$host;
  proxy_set_header X-Real-IP \$remote_addr;
  proxy_buffering off;
  proxy_request_buffering off;
  proxy_read_timeout 600s;
  proxy_send_timeout 600s;
}

# Public Claude API. Requires SNI; resolver needed for proxy_pass to host.
location /api/llm/anthropic/ {
  access_log off;
  resolver 1.1.1.1 8.8.8.8 valid=300s ipv6=off;
  proxy_pass https://api.anthropic.com/;
  proxy_http_version 1.1;
  proxy_set_header Host api.anthropic.com;
  proxy_ssl_server_name on;
  proxy_ssl_name api.anthropic.com;
  proxy_buffering off;
  proxy_request_buffering off;
  proxy_read_timeout 600s;
  proxy_send_timeout 600s;
  # Pass the user's API-key headers straight through.
  proxy_pass_request_headers on;
}

# Public Gemini API.
location /api/llm/gemini/ {
  access_log off;
  resolver 1.1.1.1 8.8.8.8 valid=300s ipv6=off;
  proxy_pass https://generativelanguage.googleapis.com/;
  proxy_http_version 1.1;
  proxy_set_header Host generativelanguage.googleapis.com;
  proxy_ssl_server_name on;
  proxy_ssl_name generativelanguage.googleapis.com;
  proxy_buffering off;
  proxy_request_buffering off;
  proxy_read_timeout 600s;
  proxy_send_timeout 600s;
  proxy_pass_request_headers on;
}
EOF

echo "[entrypoint] LLM proxy snippet written (LLM_HOST=${LLM_HOST}, LLM_LOCAL_PORT=${LLM_LOCAL_PORT}, LLM_LOCAL_B_PORT=${LLM_LOCAL_B_PORT})."
