#!/bin/sh
# Dell Discovery Canvas — LLM proxy snippet generator (v2.4.0).
#
# Generates /etc/nginx/snippets/llm-proxy.conf with three reverse-proxy
# location blocks so the browser can reach LLM endpoints without CORS:
#   /api/llm/local/*      -> http://${LLM_HOST}:${LLM_LOCAL_PORT}/
#   /api/llm/anthropic/*  -> https://api.anthropic.com/
#   /api/llm/gemini/*     -> https://generativelanguage.googleapis.com/
#
# LLM_HOST defaults to host.docker.internal (works on Docker Desktop and
# on Linux Docker 20.10+ with the host-gateway extra-hosts mapping in
# docker-compose.yml). Override per deployment by setting the env var.
#
# Invoked automatically by the upstream nginx:alpine entrypoint chain.

set -eu

SNIPPETS_DIR="/etc/nginx/snippets"
LLM_INCLUDE="${SNIPPETS_DIR}/llm-proxy.conf"

LLM_HOST="${LLM_HOST:-host.docker.internal}"
LLM_LOCAL_PORT="${LLM_LOCAL_PORT:-8000}"

mkdir -p "$SNIPPETS_DIR"

cat > "$LLM_INCLUDE" <<EOF
# Generated by docker-entrypoint.d/45-setup-llm-proxy.sh from env vars.
# LLM_HOST=${LLM_HOST}, LLM_LOCAL_PORT=${LLM_LOCAL_PORT}.

# Local self-hosted vLLM (Code LLM, VLM, etc.) — typically on the GB10.
location /api/llm/local/ {
  access_log off;
  proxy_pass http://${LLM_HOST}:${LLM_LOCAL_PORT}/;
  proxy_http_version 1.1;
  proxy_set_header Host \$host;
  proxy_set_header X-Real-IP \$remote_addr;
  proxy_read_timeout 120s;
  proxy_send_timeout 120s;
}

# Public Claude API. Requires SNI; resolver needed for proxy_pass to host.
location /api/llm/anthropic/ {
  access_log off;
  resolver 1.1.1.1 8.8.8.8 valid=300s ipv6=off;
  proxy_pass https://api.anthropic.com/;
  proxy_http_version 1.1;
  proxy_set_header Host api.anthropic.com;
  proxy_ssl_server_name on;
  proxy_ssl_name api.anthropic.com;
  proxy_read_timeout 120s;
  proxy_send_timeout 120s;
  # Pass the user's API-key headers straight through.
  proxy_pass_request_headers on;
}

# Public Gemini API.
location /api/llm/gemini/ {
  access_log off;
  resolver 1.1.1.1 8.8.8.8 valid=300s ipv6=off;
  proxy_pass https://generativelanguage.googleapis.com/;
  proxy_http_version 1.1;
  proxy_set_header Host generativelanguage.googleapis.com;
  proxy_ssl_server_name on;
  proxy_ssl_name generativelanguage.googleapis.com;
  proxy_read_timeout 120s;
  proxy_send_timeout 120s;
  proxy_pass_request_headers on;
}
EOF

echo "[entrypoint] LLM proxy snippet written (LLM_HOST=${LLM_HOST}, LLM_LOCAL_PORT=${LLM_LOCAL_PORT})."
